// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe5HAW3SaSMc3OhnJZ7CIiSTZm0Ih5NTE',
    appId: '1:741927282076:web:76a0d23daf062046e95459',
    messagingSenderId: '741927282076',
    projectId: 'final-ec753',
    authDomain: 'final-ec753.firebaseapp.com',
    storageBucket: 'final-ec753.appspot.com',
    measurementId: 'G-86VRPE6TL4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_hAnWkPLQQzB_VBKgNaL4TOkpRvuRVh0',
    appId: '1:741927282076:android:6f877f28718172afe95459',
    messagingSenderId: '741927282076',
    projectId: 'final-ec753',
    storageBucket: 'final-ec753.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfA9Oe57CDBkPvvDl0vGsP6ganKygXfxI',
    appId: '1:741927282076:ios:d0437c5678e75c7ee95459',
    messagingSenderId: '741927282076',
    projectId: 'final-ec753',
    storageBucket: 'final-ec753.appspot.com',
    iosBundleId: 'com.example.firebaseIntegration',
  );
}